version: "3.8"
services: 
  t211math333:
    container_name: t211math333
    build:
      context: .
      args:
        - JULIA_VERSION=1.6.2
    ports: 
      - "1233:1233"
    volumes: 
      - .:/home/julia/project
